-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'PLAYBACK_PAUSE';
ALTER TYPE "AuditAction" ADD VALUE 'PLAYBACK_SEEK';
ALTER TYPE "AuditAction" ADD VALUE 'PLAYBACK_COMPLETE';
ALTER TYPE "AuditAction" ADD VALUE 'RECORD_DOWNLOAD';
ALTER TYPE "AuditAction" ADD VALUE 'AUDIT_VIEW';
